### ISSUE TITLE
只会在打开网站的时候加载，而不会根据页面切换加载。

### ISSUE THREAD

**Issue by mildnes** [wheato/dLInkCopy#1]
可能我说的不够清楚，比如我在天天美剧下载的时候，搜索神盾局，打开网站之后，只会加载第四季的添加列表，而如果切换到其他的几季的话就会失效。
* 这个是第一次打开网站
![](http://cdico.cn/blog/2016-11-24-224421.jpg)
* 这个是切换了剧集之后。
![](http://cdico.cn/blog/2016-11-24-224528.jpg)

**Comment by wheato** [comment]
哦。我明白了，因为之前这一块Ajax后加载的html，所以当时探测不到。这个我去找找解决办法先。谢谢使用！

**Comment by mildnes** [comment]
@wheato 还是感谢分享。🙏

**Comment by wheato** [comment]
@mildnes 已修复这个问题
